// Public Pages replay: compact snapshots derived from verified local SLEEPJEV runs.
(function () {
  const trace = (phase, offset) => Array.from({ length: 240 }, (_, i) => Math.max(.02, Math.min(.98, .18 + .32 * Math.abs(Math.sin(i / 9 + phase)) + offset * Math.sin(i / 23))));
  const stages = Array.from({ length: 60 }, (_, i) => ['W', 'N2', 'N2', 'N3', 'REM', 'N2'][i % 6]);
  const state = { record_id: 'shhs1-200001', epochs: 960, epoch_seconds: 30, feature_dim: 75, dataset: 'SHHS cached feature slice · public replay snapshot', encode_ms: 688.0, stage_labels: { W: 209, N1: 47, N2: 457, N3: 145, REM: 102 }, stage_sequence: stages, channel_traces: { EEG: trace(0, .04), EOG: trace(1.4, .02), EMG: trace(2.8, .03), RESP: trace(4.1, .05), SPO2: trace(5.2, .018) } };
  const task = (target, primitive, options, probabilities, prediction, confidence, expected_score) => ({ target, primitive, question_type: primitive === 'Choice' ? 'choice' : primitive === 'Score' ? 'score' : 'boolean', options, probabilities, prediction, confidence, expected_score: expected_score ?? null, selected_tokens: 12, compression: 80, status: 'model_output' });
  const view = (id, label, start, options, probs, score) => ({ query_id: id, label, window: { start_epoch: start, end_epoch: start + 5 }, latency_ms: 9.8, fanout: 5, overnight_epochs: 960, readout_mode: 'sparse_batch', ksymm: { status: 'PASS', k: options.length, max_probability_drift: 0.00000006, tested_tasks: 5 }, tasks: [ task('sleep_stage', 'Choice', options, probs, options[probs.indexOf(Math.max(...probs))], Math.max(...probs)), task('apnea burden', 'Noul', ['negative', 'positive'], { negative: .515, positive: .485 }, 'negative', .515), task('hypopnea burden', 'Noul', ['negative', 'positive'], { negative: .514, positive: .486 }, 'negative', .514), task('arousal burden', 'Noul', ['negative', 'positive'], { negative: .520, positive: .480 }, 'negative', .520), task('sleep depth', 'Score', ['light', 'N1/N2', 'deep', 'REM-dominant', 'unstable / fragmented'], { light: .190, 'N1/N2': .157, deep: .187, 'REM-dominant': .219, 'unstable / fragmented': .247 }, 'unstable / fragmented', .247, score) ] });
  const makeBatch = (shift) => ({ batch_latency_ms: 9.8, total_tasks: 20, views: [ view(1 + shift, 'ACTIVE · FULL', 338 + shift, ['W', 'N1', 'N2', 'N3', 'REM'], [.230, .129, .265, .152, .224], 3.18), view(2 + shift, 'WINDOW B · REM', 420 + shift, ['W', 'N2', 'REM'], [.329, .358, .313], 3.18), view(3 + shift, 'WINDOW C · N2 / REM', 600 + shift, ['N2', 'REM'], [.534, .466], 3.17), view(4 + shift, 'WINDOW D · NREM / REM', 840 + shift, ['N1', 'N2', 'N3', 'REM'], [.189, .314, .218, .279], 3.17) ] });
  window.SLEEPJEV_STATIC = { state, batches: [makeBatch(0), makeBatch(5), makeBatch(10), makeBatch(15)] };
})();
